version : '3'
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name : mysql
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=${SEQUELIZE_DB:-pabrik_dorayaki}
      - MYSQL_ROOT_PASSWORD=${SEQUELIZE_PASSWORD:-password}
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./scripts/init.sql:/data/application/scripts/init.sql
    networks:
      - app-network

networks:
  app-network:
